version: "3.9"
services:
  redis:
    tty: true
    stdin_open: true
    image: "skelflo/redis"
    #container_name: "skelflo_nginx_1"
    build: .
    restart: "no"
    network_mode: "host"
    # ports:
    #   - "80:80"
    #   - "443:443"
    command: ["redis-server", "--bind", "0.0.0.0", "--port", "6379","--daemonize","yes"]
    volumes:
      - ./redis/data:/data
    #   - /home/skelflo/nginx/log:/var/log/nginx/
    #   - ./config/nginx.conf:/config/nginx.conf
    #   - ./config/sites-conf:/sites
    #   - ./config/logrotate:/config/logrotate
    #   - ./config/certbot/conf:/etc/letsencrypt
    #   - ./config/certbot/www:/var/www/certbot
    #   - ./script:/script