version: "3.9"
services:
  web:
    tty: true
    stdin_open: true
    image: "skelflo/nginx"
    container_name: "skelflo_nginx_1"
    build: .
    restart: "no"
    network_mode: "host"
    # ports:
    #   - "80:80"
    #   - "443:443"
    volumes:
      - /home/skelflo/nginx/log:/var/log/nginx/
      - ./config/sites-conf:/sites
      - ./config/logrotate:/logrotate
      - ./config/certbot/conf:/etc/letsencrypt
      - ./config/certbot/www:/var/www/certbot
      - ./script:/script
  certbot:
    image: certbot/certbot
    #entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    volumes:
      - ./config/certbot/conf:/etc/letsencrypt
      - ./config/certbot/www:/var/www/certbot