version: "3.9"
services:
  web:
    tty: true
    stdin_open: true
    image: "skelflo/sce"
    container_name: "skelflo_sce_1"
    networks:
      default:
        external:
          name: bridge
    build: .
    restart: "no"
    ports:
      - "9091:80"
    volumes:
      - /home/skelflo/sce/sites/sce:/var/www/html
      - ./script:/script
      - ./config:/config