version: "3.9"
services:
  web:
    tty: true
    stdin_open: true
    image: "skelflo/sce"
    container_name: "skelflo_sce_1"
    build: .
    restart: "no"
    ports:
      - "9091:80"
    volumes:
      - /home/skelflo/sce/sites:/var/www/html
      - ./script:/script
      - ./config:/config
    command: /build/add_hosts.sh