version: "3.9"
services:
  web:
    tty: true
    stdin_open: true
    image: "skelflo/adadosa"
    container_name: "skelflo_adadosa_1"
    network_mode: bridge
    build: .
    restart: "no"
    ports:
      - "9092:80"
    volumes:
      - /home/skelflo/adadosa/sites/adadosa:/var/www/html
      - ./script:/script
      - ./config:/config